language: node_js
node_js:
  - '4.0'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-hyperledger-composer-network' ]; then cd .. && eval "mv $currentfolder generator-hyperledger-composer-network" && cd generator-hyperledger-composer-network; fi

