language: node_js
node_js:
  - '4.0'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ethdapp' ]; then cd .. && eval "mv $currentfolder generator-ethdapp" && cd generator-ethdapp; fi

